# Generated by Django 4.2 on 2023-05-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_QA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTestInput',
            fields=[
                ('index', models.AutoField(db_column='Index', primary_key=True, serialize=False)),
                ('energyID', models.IntegerField(db_column='energyID')),
                ('input1', models.DecimalField(blank=True, db_column='input1', decimal_places=4, max_digits=10, null=True)),
                ('input2', models.DecimalField(blank=True, db_column='input2', decimal_places=4, max_digits=10, null=True)),
                ('input3', models.DecimalField(blank=True, db_column='input3', decimal_places=4, max_digits=10, null=True)),
                ('input4', models.DecimalField(blank=True, db_column='input4', decimal_places=4, max_digits=10, null=True)),
                ('configID', models.IntegerField(db_column='configID')),
            ],
            options={
                'db_table': 'daily_test_input',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='dailytest',
            options={'managed': True},
        ),
    ]
