# Generated by Django 4.2 on 2023-06-19 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_QA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlynxmeasurement',
            name='measurementid',
            field=models.ForeignKey(blank=True, db_column='measurementid', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='daily_QA.dailytest'),
        ),
    ]
