# Generated by Django 4.2 on 2023-05-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_QA', '0002_dailytestinput_alter_dailytest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytest',
            name='gantry',
            field=models.IntegerField(db_column='Gantry', null=True),
        ),
    ]
