# Generated by Django 4.2 on 2023-12-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_QA', '0002_dailytest_dailytestdraft_dailytestinput_dlynxconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytest',
            name='user',
            field=models.CharField(blank=True, db_column='user', max_length=45, null=True),
        ),
    ]
