# Generated by Django 4.2 on 2023-06-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_QA', '0004_dailytestdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytestdraft',
            name='mlicid',
            field=models.IntegerField(blank=True, db_column='MlicID', null=True),
        ),
    ]
