# Generated by Django 4.2 on 2023-06-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_QA', '0005_dailytestdraft_mlicid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytestdraft',
            name='mlic100_range',
            field=models.DecimalField(blank=True, db_column='Mlic100_range', decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailytestdraft',
            name='mlic170_range',
            field=models.DecimalField(blank=True, db_column='Mlic170_range', decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailytestdraft',
            name='mlic226_range',
            field=models.DecimalField(blank=True, db_column='Mlic226_range', decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailytestdraft',
            name='mlic70_range',
            field=models.DecimalField(blank=True, db_column='Mlic70_range', decimal_places=3, max_digits=10, null=True),
        ),
    ]
